#!/bin/sh
#
#  Launch the application.
#
#  1.  If we're launched by a username of the form /^s-dns/ then
#     we bind to the port of the user-id.
#
#  2.  We log to logs/$(date).log
#
#


# Default port
port=5001

# Magic-user?
if [ "$USER" = "s-dns-org" ]; then
    port=$(id -u)
fi

# Ensure we have a log-directory
mkdir logs/ || true

# Launch
echo "Launching on 127.0.0.1:$port"
exec plackup -s Twiggy --workers=4 --host 127.0.0.1 -p $port -a ./bin/dns-api --access-log logs/access.$(date +%Y-%m-%d).log -E production
